#!/bin/sh

if [ -z "$1" ]; then
    echo "Usage: $0 path-to-vm.vmwarevm"
    exit 1
fi

PATH=$PATH:"/Applications/VMware Fusion.app/Contents/Library/"
VM=$1

vmrun -T fusion start "${VM}"
vmrun -T fusion -gu "${GUEST_USER:-IEUser}" -gp "${GUEST_PASSWORD:-Passw0rd!}" runProgramInGuest "${VM}" reg.exe ADD "HKLM\SOFTWARE\Microsoft\Internet Explorer\Setup\10.0" /v DoNotAllowIE10 /t REG_DWORD /d 1 /f
